language: ruby
sudo: false
cache: bundler
rvm:
  - 2.3.8
  - 2.4.5
  - 2.5.5
  - 2.6.3
gemfile:
  - Gemfile
  - gemfiles/activesupport-5.0.gemfile
  - gemfiles/activesupport-5.1.gemfile
  - gemfiles/activesupport-6.0.gemfile
before_script:
  - gem update --system
matrix:
  exclude:
    - gemfile: gemfiles/activesupport-6.0.gemfile
      rvm: 2.3.8
    - gemfile: gemfiles/activesupport-6.0.gemfile
      rvm: 2.4.5
